default_config:

logger:
  default: error
  logs:
    custom_components.pool_pump: debug

automation: !include automations.yaml

pool_pump:
  switch_entity_id: input_boolean.fake_switch
  pool_pump_mode_entity_id: input_select.mode
  swimming_season_entity_id: input_boolean.season
  run_pool_pump_hours_swimming_season_entity_id: input_number.duree_pleine_saison
  run_pool_pump_hours_off_season_entity_id: input_number.duree_off_saison